-- | Pretty-print compiled peers into @wg-quick@ configuration files.
module WgForge.Renderer (
  renderConfig,
) where

import Data.ByteString (ByteString)
import qualified Data.ByteString.Char8 as BS8
import Data.IP (AddrRange, IPv4)
import qualified Data.Map.Strict as Map
import Data.Set (Set)
import qualified Data.Set as Set
import Data.Text (Text)
import Prettyprinter
import Prettyprinter.Render.Text (renderStrict)

import WgForge.Compiler
import WgForge.Key
import WgForge.Spec

-- | Render a single compiled peer as a complete @wg-quick@ config file:
--   the @[Interface]@ block followed by one @[Peer]@ block per entry.
renderConfig :: PeerName -> CompiledPeer -> Text
renderConfig pn p =
  renderStrict . layoutPretty defaultLayoutOptions $
    blocks (header : renderInterface pn p : peerBlocks) <> line
 where
  peerBlocks = [renderPeerEntry t e | (t, e) <- Map.toAscList (peerEntries p)]

header :: Doc ann
header =
  vsep
    [ "# Generated by wg-forge - do not edit.",
      "# Source of truth: the network spec."
    ]

renderInterface :: PeerName -> CompiledPeer -> Doc ann
renderInterface pn p =
  vsep $
    [ "[Interface]",
      comment pn,
      field "PrivateKey" (renderKey (encodePrivateKey (ifacePrivKey p))),
      field "Address" (viaShow (ifaceAddress p))
    ]
      ++ optional "ListenPort" renderPort (ifaceListenPort p)

renderPeerEntry :: PeerName -> CompiledPeerEntry -> Doc ann
renderPeerEntry pn e =
  vsep $
    [ "[Peer]",
      comment pn,
      field "PublicKey" (renderKey (encodePublicKey (pubKey e)))
    ]
      ++ optional "Endpoint" renderEndpoint (WgForge.Compiler.endpoint e)
      ++ [field "AllowedIPs" (renderAllowedIps (allowedIps e))]
      ++ optional "PersistentKeepalive" pretty (keepalive e)

-- | @key = value@.
field :: Text -> Doc ann -> Doc ann
field k v = pretty k <+> "=" <+> v

-- | A single @key = value@ line, or nothing when the value is absent.
optional :: Text -> (a -> Doc ann) -> Maybe a -> [Doc ann]
optional k render = maybe [] (\x -> [field k (render x)])

-- | A @# peer-name@ identifying comment.
comment :: PeerName -> Doc ann
comment (PeerName t) = "#" <+> pretty t

renderKey :: ByteString -> Doc ann
renderKey = pretty . BS8.unpack

renderPort :: Port -> Doc ann
renderPort (Port w) = pretty w

renderEndpoint :: Endpoint -> Doc ann
renderEndpoint (Endpoint h pt) = renderHost h <> ":" <> renderPort pt

renderHost :: HostOrIp -> Doc ann
renderHost (HostName t) = pretty t
renderHost (HostIp ip) = viaShow ip

-- | Comma-separated @AllowedIPs@ in ascending order.
renderAllowedIps :: Set (AddrRange IPv4) -> Doc ann
renderAllowedIps = hsep . punctuate comma . map viaShow . Set.toAscList

-- | Stack blocks vertically, separated by a blank line.
blocks :: [Doc ann] -> Doc ann
blocks = concatWith (\a b -> a <> line <> line <> b)
